In [1]:
import numpy as np

In [6]:
# Simple Arithematic
a = np.array([1,2,3,4,5,6],dtype='f')
b = np.array([10,20,30,40,50,60],dtype='f')
# Addition
arr1 = np.add(a,b)
# Subtraction
arr2 = np.subtract(b,a)
# Multiplication
arr3 = np.multiply(a,b)
# Division
arr4 = np.divide(a,b)
# Power
arr5 = np.power(b,a)
# Remainder
arr6 = np.remainder(a,b)
# Quotient and Mod
arr7 = np.divmod(b,a)
# Absolute Values
arr8_1 = np.absolute(a)
arr8_2 = np.absolute(b)
print(arr1,arr2,arr3,arr4,arr5,arr6,arr7,arr8_1,arr8_2,sep="\n")

[11. 22. 33. 44. 55. 66.]
[ 9. 18. 27. 36. 45. 54.]
[ 10.  40.  90. 160. 250. 360.]
[0.1 0.1 0.1 0.1 0.1 0.1]
[1.0000e+01 4.0000e+02 2.7000e+04 2.5600e+06 3.1250e+08 4.6656e+10]
[1. 2. 3. 4. 5. 6.]
(array([10., 10., 10., 10., 10., 10.], dtype=float32), array([0., 0., 0., 0., 0., 0.], dtype=float32))
[1. 2. 3. 4. 5. 6.]
[10. 20. 30. 40. 50. 60.]
